/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewerRouteImport } from './routes/reviewer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewerIndexRouteImport } from './routes/reviewer/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ReviewerQueueRouteImport } from './routes/reviewer/queue'
import { Route as DashboardVaultRouteImport } from './routes/dashboard/vault'
import { Route as DashboardSupportRouteImport } from './routes/dashboard/support'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardLegalAidRouteImport } from './routes/dashboard/legal-aid'
import { Route as DashboardClaimsRouteImport } from './routes/dashboard/claims'
import { Route as DashboardCasesNewIndexRouteImport } from './routes/dashboard/cases/new/index'

const ReviewerRoute = ReviewerRouteImport.update({
  id: '/reviewer',
  path: '/reviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewerIndexRoute = ReviewerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewerRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ReviewerQueueRoute = ReviewerQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => ReviewerRoute,
} as any)
const DashboardVaultRoute = DashboardVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLegalAidRoute = DashboardLegalAidRouteImport.update({
  id: '/legal-aid',
  path: '/legal-aid',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClaimsRoute = DashboardClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCasesNewIndexRoute = DashboardCasesNewIndexRouteImport.update({
  id: '/cases/new/',
  path: '/cases/new/',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/reviewer': typeof ReviewerRouteWithChildren
  '/dashboard/claims': typeof DashboardClaimsRoute
  '/dashboard/legal-aid': typeof DashboardLegalAidRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/vault': typeof DashboardVaultRoute
  '/reviewer/queue': typeof ReviewerQueueRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/reviewer/': typeof ReviewerIndexRoute
  '/dashboard/cases/new/': typeof DashboardCasesNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard/claims': typeof DashboardClaimsRoute
  '/dashboard/legal-aid': typeof DashboardLegalAidRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/vault': typeof DashboardVaultRoute
  '/reviewer/queue': typeof ReviewerQueueRoute
  '/dashboard': typeof DashboardIndexRoute
  '/reviewer': typeof ReviewerIndexRoute
  '/dashboard/cases/new': typeof DashboardCasesNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/reviewer': typeof ReviewerRouteWithChildren
  '/dashboard/claims': typeof DashboardClaimsRoute
  '/dashboard/legal-aid': typeof DashboardLegalAidRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/vault': typeof DashboardVaultRoute
  '/reviewer/queue': typeof ReviewerQueueRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/reviewer/': typeof ReviewerIndexRoute
  '/dashboard/cases/new/': typeof DashboardCasesNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/reviewer'
    | '/dashboard/claims'
    | '/dashboard/legal-aid'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/vault'
    | '/reviewer/queue'
    | '/dashboard/'
    | '/reviewer/'
    | '/dashboard/cases/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard/claims'
    | '/dashboard/legal-aid'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/vault'
    | '/reviewer/queue'
    | '/dashboard'
    | '/reviewer'
    | '/dashboard/cases/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/reviewer'
    | '/dashboard/claims'
    | '/dashboard/legal-aid'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/vault'
    | '/reviewer/queue'
    | '/dashboard/'
    | '/reviewer/'
    | '/dashboard/cases/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ReviewerRoute: typeof ReviewerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reviewer': {
      id: '/reviewer'
      path: '/reviewer'
      fullPath: '/reviewer'
      preLoaderRoute: typeof ReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewer/': {
      id: '/reviewer/'
      path: '/'
      fullPath: '/reviewer/'
      preLoaderRoute: typeof ReviewerIndexRouteImport
      parentRoute: typeof ReviewerRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/reviewer/queue': {
      id: '/reviewer/queue'
      path: '/queue'
      fullPath: '/reviewer/queue'
      preLoaderRoute: typeof ReviewerQueueRouteImport
      parentRoute: typeof ReviewerRoute
    }
    '/dashboard/vault': {
      id: '/dashboard/vault'
      path: '/vault'
      fullPath: '/dashboard/vault'
      preLoaderRoute: typeof DashboardVaultRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/legal-aid': {
      id: '/dashboard/legal-aid'
      path: '/legal-aid'
      fullPath: '/dashboard/legal-aid'
      preLoaderRoute: typeof DashboardLegalAidRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/claims': {
      id: '/dashboard/claims'
      path: '/claims'
      fullPath: '/dashboard/claims'
      preLoaderRoute: typeof DashboardClaimsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cases/new/': {
      id: '/dashboard/cases/new/'
      path: '/cases/new'
      fullPath: '/dashboard/cases/new/'
      preLoaderRoute: typeof DashboardCasesNewIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardClaimsRoute: typeof DashboardClaimsRoute
  DashboardLegalAidRoute: typeof DashboardLegalAidRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardVaultRoute: typeof DashboardVaultRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCasesNewIndexRoute: typeof DashboardCasesNewIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardClaimsRoute: DashboardClaimsRoute,
  DashboardLegalAidRoute: DashboardLegalAidRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardVaultRoute: DashboardVaultRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCasesNewIndexRoute: DashboardCasesNewIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ReviewerRouteChildren {
  ReviewerQueueRoute: typeof ReviewerQueueRoute
  ReviewerIndexRoute: typeof ReviewerIndexRoute
}

const ReviewerRouteChildren: ReviewerRouteChildren = {
  ReviewerQueueRoute: ReviewerQueueRoute,
  ReviewerIndexRoute: ReviewerIndexRoute,
}

const ReviewerRouteWithChildren = ReviewerRoute._addFileChildren(
  ReviewerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ReviewerRoute: ReviewerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
